query GetUserRepositories ($first: Int, $after: String, $before: String) {
 user(login: "Aliceretool") {
   repositories(first: $first, after: $after, before: $before, privacy: PUBLIC) {
     edges {
       node {
         name
         description
         url
       }
       cursor
     }
     pageInfo {
       startCursor
       endCursor
       hasNextPage
       hasPreviousPage
     }
   }
 }
}