query GetUserRepositories($login: String!) {
  user(login: $login) {
    repositories(first: 10, privacy: PUBLIC) {
      edges {
        node {
          name
          description
          url
        }
        cursor
      }
      pageInfo {
        startCursor
        endCursor
        hasNextPage
        hasPreviousPage
      }
    }
  }
}