version: 43.0.9
pageUuid: dd52d30e-94fa-11ee-9c0d-87ca45934cbf
appTemplate:
  preloadedAppJavaScript: |-
    function myCustomHelperApp(str){
      return str + 'preloaded js again'
    }
  notificationsSettings:
    object:
      globalQueryShowFailureToast: true
      globalQueryShowSuccessToast: true
      globalQueryToastDuration: 4.5
  shortlink: false
  version: 3.35.0
  experimentalDataTabEnabled: true
