<PlaygroundQuery
  id="test"
  adhocResourceType={null}
  data={null}
  resourceType="restapi"
>
  <RESTQuery
    allowedGroupIds={[]}
    allowedGroups={[]}
    events={[]}
    importedQueryDefaults={{}}
    importedQueryInputs={{}}
    privateParams={[]}
    query="browse/new-releases"
    queryTimeout="100000"
    retoolVersion="3.26.6"
    watchedParams={[]}
  />
</PlaygroundQuery>
