id: params
type: datasource
subtype: JavascriptQuery
resourceName: JavascriptQuery
template:
  ordered:
    - query: return null
    - evalType: script
createdAt: 2026-01-20T09:35:46.969Z
blockData:
  top: 48
  left: 48
  uuid: 386459f5-e63b-43ff-a03c-17f1728f18f1
  options: {}
  pluginId: params
  blockType: webhook
  editorType: JavascriptQuery
  isMinimized: false
  resourceName: webhook
  incomingOnSuccessEdges: []
