id: params
type: datasource
subtype: JavascriptQuery
resourceName: JavascriptQuery
template:
  ordered:
    - query: return null
    - evalType: script
createdAt: 2026-02-27T13:38:23.896Z
blockData:
  top: 48
  left: 48
  uuid: 03312cb7-e396-4d01-b0c0-1671796caa3b
  options: {}
  pluginId: params
  blockType: webhook
  editorType: JavascriptQuery
  isMinimized: false
  resourceName: webhook
  incomingOnSuccessEdges: []
