version: 43.0.9
pageUuid: 87f0e76a-b9e0-11ee-bf4f-dff4930dcfe2
appTemplate:
  urlFragmentDefinitions:
    - ordered:
        - name: id
        - value: '{{numberInput1.value}}'
  shortlink: false
  version: 3.18.6
  experimentalDataTabEnabled: true
