version: 43.0.9
pageUuid: 4468c33e-02e0-11ef-821f-4fe1d1e9506b
appTemplate:
  notificationsSettings:
    object:
      globalQueryShowFailureToast: true
      globalQueryShowSuccessToast: false
      globalQueryToastDuration: 4.5
  shortlink: false
  version: 3.33.24
  experimentalDataTabEnabled: true
