version: 43.0.9
pageUuid: 25ef63c8-db11-11ee-951b-b7112ebc49c1
appTemplate:
  preloadedAppJavaScript: |-
    window.greeting = "hello
      world
        line 
          three "
  shortlink: false
  version: 3.33.3
  experimentalDataTabEnabled: true
