version: 43.0.9
pageUuid: 0a63423e-1b11-11ee-94a4-8f8096606c1e
appTemplate:
  appMaxWidth: 1560px
  experimentalFeatures:
    object:
      sourceControlTemplateDehydration: false
      multiplayerEditingEnabled: false
  version: 3.36.0
  experimentalDataTabEnabled: true
