version: 43.0.9
pageUuid: 5f0a6a28-7404-11ee-b1d2-3f21f494057f
appTemplate:
  inAppRetoolPillAppearance: POWERED_BY_RETOOL
  notificationsSettings:
    object:
      globalQueryShowFailureToast: true
      globalQueryShowSuccessToast: true
      globalQueryToastDuration: 4.5
  appTesting:
    object:
      testSuites:
        array: []
      tests:
        object: {}
  customDocumentTitleEnabled: true
  version: 3.64.0
  experimentalDataTabEnabled: true
