<PlaygroundQuery
  id="demo test"
  adhocResourceType={null}
  data={null}
  resourceType="postgresql"
>
  <SqlQuery
    _additionalScope={[]}
    actionType=""
    allowedGroupIds={[]}
    allowedGroups={[]}
    bulkUpdatePrimaryKey=""
    dataArray={[]}
    doNotThrowOnNoOp={false}
    editorMode="sql"
    enableBulkUpdates={false}
    events={[]}
    filterBy=""
    importedQueryDefaults={{}}
    importedQueryInputs={{}}
    privateParams={[]}
    query={include("./lib/demo test.sql", "string")}
    queryTimeout="100000"
    recordId=""
    records=""
    retoolVersion="3.37.0"
    showUpdateSetValueDynamicallyToggle={false}
    tableName=""
    updateSetValueDynamically={true}
    warningCodes={[]}
    watchedParams={[]}
  />
</PlaygroundQuery>
