query getPurchaseOrderTextile($id: ID!) {
  purchaseOrderTextile(id: $id) {
    id
    sellerID
    sellerName
    sellerCode
    sellerDivisionID
    sellerDivisionName
    sellerDivisionCode
    sellerSectionID
    sellerSectionName
    sellerSectionCode
    sellerGroupName
    sellerGroupCode

    code
    orderDate
    purchaseSlipTypeName
    purchaseSlipTypeCode
    purchaseSlipTypeRequestCategory
    partnerID
    purchasePartnerName
    purchasePartnerCode
    purchasePaymentConditionName
    purchasePaymentConditionCode
    partnerNote

    partnerShipID
    partnerShipName
    partnerShipCode
    partnerShipTel
    partnerShipZipcode
    partnerShipCountryName
    partnerShipPrefectureName
    partnerShipAddress

    totalPriceJpy
    externalNote
    internalNote

    completionFlag
    status
    createdAt
    updatedAt

    archived
    attachedFiles {
      name
      fileId
      contentType
      fileSize
    }

    creatorID
    creatorCode
    creatorName
    creatorDivisionID
    creatorDivisionCode
    creatorDivisionName
    creatorSectionID
    creatorSectionCode
    creatorSectionName
    creatorGroupID
    creatorGroupCode

    bulkCode

    registrationDate
    productGroupID
    intercomms
    portOfLoading
    portOfDischarge
    allowableValue
    currencyID
    currencyName
    exchangeReservationNumber
    exchangeRate
    sellerGroupName
    creatorGroupName
    totalPrice
  }
}