query($id: ID){
  installerApplication(where: {id: $id}){
    id
    applicationReviewStatus
    waitingOnIRCDiscussion
    isPendingMoreInformation
    applicationStalled
    currentOperatingStates
    externalId
    returnedToApplicantForRevision
    requiresCaf
    applicationProcessor{
      id
      name
    }
    applicationReviewer{
      id
      name
      firstName
      middleInitial
      lastName
    }
    applicationPriority
    applicationSubmitted
    insuranceRequirementsMet
    portalKey
    requestor{
      id
      fullName
      title
    }
    account{
      id
      name
      size
      accountManagerName
      accountManagerEmail
      leadSource
      externalId
    }
    applicationCompany{
      id
      timeInBusiness
      numberOfInstallsLastYear
      volumePotential
      numberOfReviews
      averageReviewScore
      negativeReviews
      ohmRatingLTM
    }
    applicationSectionStatus {
      id
      installerAgreementReview
      installerAgreementKickbackNotes
      companyProfileReview
      companyProfileKickbackNotes
      insurancesReview
      insurancesKickbackNotes
      financialsReview
      financialsKickbackNotes
      statesLicensesReview
      statesLicensesKickbackNotes
      creditAuthorizationReview
      creditAuthorizationKickbackNotes
      principalsReview
      principalsKickbackNotes
    }
    agreement {
      id
      invalidatedAt
    }
    applicationResubmitted
    applicationProcessorClaimed
    applicationReviewerClaimed
    returnedToAccountManager
    returnedToApplicationProcessing
    applicationProcessingCompleted
    applicationDecision
    applicationDecisionDate
    primaryDenialReason
    hasCustomInstallerAgreement
  }
}