version: 43.0.9
pageUuid: fa9a053e-8232-11ee-bcd8-238bef26a585
appTemplate:
  appMaxWidth: 100%
  experimentalFeatures:
    object:
      sourceControlTemplateDehydration: false
      multiplayerEditingEnabled: false
      disableMultiplayerEditing: false
  queryStatusVisibility: false
  rootScreen: null
  version: 3.24.6
  markdownLinkBehavior: auto
  experimentalDataTabEnabled: true
