version: 43.0.9
pageUuid: fa9a053e-8232-11ee-bcd8-238bef26a585
appTemplate:
  appMaxWidth: 800px
  notificationsSettings:
    object:
      globalQueryShowFailureToast: true
      globalQueryShowSuccessToast: true
      globalQueryToastDuration: 4.5
  version: 3.56.0
  experimentalDataTabEnabled: true
